### ISSUE TITLE
Update plugins to null safety and lumberdash 3.0

### ISSUE THREAD

**Issue by maxifom** [jorgecoca/lumberdash#70]
Currently we can update lumberdash to 3.0.0 with null safety, but its pretty much useless, as plugins depend on lumberdash 2

**Comment by fabiomcarneiro** [comment]
If we go to pub.dev and check for example : https://pub.dev/packages/colorize_lumberdash/score

`Support up-to-date dependencies` that it requires Lumberdash 3.0.0 .

Are you using the version 3.0.0 of the plugins?

**Comment by maxifom** [comment]
> If we go to pub.dev and check for example : https://pub.dev/packages/colorize_lumberdash/score
> 
> 
> 
> `Support up-to-date dependencies` that it requires Lumberdash 3.0.0 .
> 
> 
> 
> Are you using the version 3.0.0 of the plugins?
> 
> 
> 
> 

Using print_lumberdash which is 2.1.0 https://pub.dev/packages/print_lumberdash

![image](https://user-images.githubusercontent.com/20924207/111017851-92db8780-83d7-11eb-8675-b5879d111017.png)

**Comment by fabiomcarneiro** [comment]
I see the issue. Print_lumberdash is under @jorgecoca ownership in pub.dev so it wasn't updated with the others.

Meanwhile you could use it directly with a git source:

```yaml
dependencies:
  print_lumberdash:
    git:
      url: git@github.com:bmw-tech/lumberdash.git
      path: plugins/print_lumberdash
```
